FROM mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-ltsc2022 AS tests

# Monkey's Audio only ships as an installer, and nanoserver can't run it or 7-Zip (no WOW64 for 32-bit exes,
# no user32/gdi32 for a GUI installer, and its built-in tar doesn't support the LZMA/.7z format either).
# So unpack it in a full Windows image instead, then copy just MAC.exe into the nanoserver stage below.
FROM mcr.microsoft.com/windows/servercore:ltsc2022 AS ape-decoder

RUN mkdir c:\tools
RUN curl --location --output c:\tools\7zr.exe https://www.7-zip.org/a/7zr.exe
RUN curl --location --output c:\tools\7z-extra.7z https://github.com/ip7z/7zip/releases/download/26.02/7z2602-extra.7z
RUN c:\tools\7zr.exe x c:\tools\7z-extra.7z -oc:\tools\7z-extra -y
RUN del c:\tools\7z-extra.7z

# MAC.exe is assumed to be in the root dir of the installer
RUN mkdir c:\decoder\ape-setup
RUN curl --location --fail --output c:\decoder\ape-setup\setup.exe https://monkeysaudio.com/x64
RUN dir c:\decoder\ape-setup\setup.exe
RUN c:\tools\7z-extra\x64\7za.exe x c:\decoder\ape-setup\setup.exe -oc:\decoder\ape-setup\extracted -y
RUN copy c:\decoder\ape-setup\extracted\MAC.exe c:\decoder\MAC.exe
RUN rmdir /s /q c:\decoder\ape-setup

FROM tests AS tests-e2e

# Install FLAC
RUN mkdir c:\decoder
RUN curl --location --output c:\decoder\flac.zip https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.5.0-win.zip
RUN tar --extract --file c:\decoder\flac.zip --directory c:\decoder
RUN del c:\decoder\flac.zip

ENV FLACHASH_TEST_DECODER=c:\\decoder\\flac-1.5.0-win\\Win64\\flac.exe

COPY --from=ape-decoder c:\decoder\MAC.exe c:\decoder\MAC.exe

ENV FLACHASH_TEST_DECODER_APE=c:\\decoder\\MAC.exe
