services:
  tests:
    # Dockerfile used here simply to have base image specified in one place (between this and e2e tests)
    build:
      context: .
      dockerfile: Dockerfile.win
      target: tests
    image: flachasher-tests-win
    working_dir: "c:\\src"
    entrypoint:
     - dotnet
    command:
     - test
     - FlacHasher.sln
     - --configuration
     - Release
     - /p:EnableWindowsTargeting=true
     # Ignore E2E tests
     - --filter
     - FullyQualifiedName!~Andy.FlacHash.Application.Cmd.E2E
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
      # Use a different output folder - so it doesn't clash with the host's builds
      # Put the build files on the host it gets reused between the `docker-compose run` in Workflow steps
      UseArtifactsOutput: "true"
      ArtifactsPath: "c:\\src\\build-output"
    volumes:
      - type: bind
        source: .
        target: "c:\\src"

  tests_e2e:
    extends:
      service: tests
    build:
      context: .
      dockerfile: Dockerfile.win
      target: tests-e2e
    image: flachasher-tests-e2e-win