FROM mcr.microsoft.com/dotnet/sdk:8.0 AS tests

FROM tests AS tests-e2e

# Install FLAC
RUN apt-get update \
    && apt-get install --yes --no-install-recommends flac \
    && rm -rf /var/lib/apt/lists/*

ENV FLACHASH_TEST_DECODER_FLAC=/usr/bin/flac
