services:
  tests:
    # Dockerfile used here simply to have base image specified in one place (between this and e2e tests)
    build:
      context: .
      dockerfile: Dockerfile.lnx
      target: tests
    image: flachasher-tests-lnx
    working_dir: /src
    entrypoint:
     - dotnet
    command:
     - test
     - FlacHasher.sln
     - --configuration
     - Release
     - /p:EnableWindowsTargeting=true
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
      # Use a different output folder - so it doesn't clash with the host's builds
      # Put the build files on the host it gets reused between the `docker-compose run` in Workflow steps
      UseArtifactsOutput: "true"
      ArtifactsPath: /src/build-output
    volumes:
      - type: bind
        source: .
        target: /src

  tests_e2e:
    extends:
      service: tests
    build:
      context: .
      dockerfile: Dockerfile.lnx
      target: tests-e2e
    image: flachasher-tests-e2e-lnx