# Same tests, just ran via Docker, not directly on the host (GH runner)
name: Run Tests on Windows (Docker)

on:
    workflow_dispatch:
    pull_request:
      branches:
        - "**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: windows-2022
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker compose --file docker-compose-win.yml pull tests
      - name: Run Tests
        run: docker compose --file docker-compose-win.yml run --rm tests
