name: Run Tests on Windows (Docker, HTML report)

on:
    workflow_dispatch:
    pull_request:
      branches:
        - "**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: windows-2022
    timeout-minutes: 30     # Because it installs extra stuff
    env:
      SLN_ARGS: FlacHasher.sln --configuration Release

    steps:
      - uses: actions/checkout@v4
      - run: mkdir TestResults

      - name: Pull the image
        run: docker compose --file docker-compose-win.yml pull tests_report
      
      - name: Install Pandoc
        run: choco install pandoc -y

      # Target "tests" service (not "tests_report") because "tests_report" overrides the
      # entrypoint to "cmd /c run-tests-w-report.cmd", so any args passed here would go to cmd, not dotnet.
      # Both services share the same image so build output would be the same
      - name: Build
        run: docker compose --file docker-compose-win.yml run --rm tests build ${{ env.SLN_ARGS }} /p:EnableWindowsTargeting=true
      
      - name: Run Tests
        id: run-tests
        continue-on-error: true
        run: docker compose --file docker-compose-win.yml run --rm tests_report
      
      - uses: actions/upload-artifact@v4
        id: report-upload-steps
        with:
          name: test-repor-win-${{ github.sha }}
          path: TestResults
          retention-days: 1
      
      - name: Convert all HTML files to a single Markdown file (separate sections for each file)
        shell: bash
        run: |
          outfile="TestResults/combined_report.md"
          rm -f "$outfile"

          for file in TestResults/*.html; do
            name="$(basename "$file")"
            title="${name%.html}"  # strip .html if desired

            {
              echo "<details>"
              echo "<summary><strong>${title}</strong></summary>"
              echo ""
              pandoc "$file" -f html -t gfm
              echo ""
              echo "</details>"
              echo ""
            } >> "$outfile"
          done
      
      - name: Add the Report to the Summary
        shell: bash
        run: |
          artifact_id="${{ steps.report-upload-steps.outputs.artifact-id }}"
          artifact_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${artifact_id}"

          echo "### Test Report" >> $GITHUB_STEP_SUMMARY
          {
            echo ""
            echo "[Download Reports Zipped](${artifact_url})"
            echo ""
          } >> $GITHUB_STEP_SUMMARY

          cat TestResults/combined_report.md >> $GITHUB_STEP_SUMMARY
      
      - name: Fail the job on test failure
        if: steps.run-tests.outcome == 'failure'
        run: |
          echo "Tests failed — marking job as failed."
          exit 1