name: Runs Tests on Linux (Docker)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:

  # This compiles the output on the host - it doesn't build an image with compiled output.
  # That's because I want to have minimal differences between local and remote build set up,
  # and locally, I want to be able to run these tests without copying source into the image.
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SLN_ARGS: FlacHasher.sln --configuration Release /p:EnableWindowsTargeting=true

    steps:
      - uses: actions/checkout@v4
      - name: Pull the image
        run: docker compose --file docker-compose-lnx.yml pull tests
      
      # Compiled output goes into a host's directory, so it's accessible in the next step (compose run )
      - name: Build
        run: docker compose --file docker-compose-lnx.yml run --rm tests build ${{ env.SLN_ARGS }}
      - name: Run Tests
        run: docker compose --file docker-compose-lnx.yml run --rm tests test ${{ env.SLN_ARGS }}