# Same tests, just ran via Docker, not directly on the host (GH runner)
name: Run Tests on Windows (Docker)

on:
    workflow_dispatch:
    pull_request:
      branches:
        - "**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # For the reason it compiles the output on the host, not in the image, see the comment in the Linux workflow file
  tests:
    runs-on: windows-2022
    timeout-minutes: 20
    env:
      SLN_ARGS: FlacHasher.sln --configuration Release /p:EnableWindowsTargeting=true

    steps:
      - uses: actions/checkout@v4
      - name: Pull the image
        run: docker compose --file docker-compose-win.yml pull tests
      - name: Build
        run: docker compose --file docker-compose-win.yml run --rm tests build ${{ env.SLN_ARGS }}
      # E2E tests are excluded here
      - name: Run Unit Tests
        run: docker compose --file docker-compose-win.yml run --rm tests test ${{ env.SLN_ARGS }} --filter "FullyQualifiedName!~Andy.FlacHash.Application.Cmd.E2E"